application: dropmocks
version: 1
runtime: python
api_version: 1

derived_file_type:
- python_precompiled


handlers:
- url: /s
  static_dir: files

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
